require 'VRAPI/VRAPI.rb'
require 'VRAPI/VRAPIMappingRegistry.rb'
require 'soap/rpc/driver'

module VRAPI

class VRAPIPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://api.verticalresponse.com/1.0/VRAPI"
  NsC_1_0 = "VR/API/1_0"

  Methods = [
    [ XSD::QName.new(NsC_1_0, "addListMember"),
      "VR/API/1_0#addListMember",
      "addListMember",
      [ ["in", "args", ["VRAPI::AddListMemberArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "addListMemberArgs"]],
        ["retval", "result", ["VRAPI::ListMember", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ListMember"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "appendFileToList"),
      "VR/API/1_0#appendFileToList",
      "appendFileToList",
      [ ["in", "args", ["VRAPI::AppendFileToListArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "appendFileToListArgs"]],
        ["retval", "result", ["VRAPI::AppendFileToListResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "appendFileToListResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "appendFileToListBackground"),
      "VR/API/1_0#appendFileToListBackground",
      "appendFileToListBackground",
      [ ["in", "args", ["VRAPI::AppendFileToListArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "appendFileToListArgs"]],
        ["retval", "background_task_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "appendTemplateCampaignModule"),
      "VR/API/1_0#appendTemplateCampaignModule",
      "appendTemplateCampaignModule",
      [ ["in", "args", ["VRAPI::AppendTemplateCampaignModuleArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "appendTemplateCampaignModuleArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "calculateCampaignAudience"),
      "VR/API/1_0#calculateCampaignAudience",
      "calculateCampaignAudience",
      [ ["in", "args", ["VRAPI::CalculateCampaignAudienceArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "calculateCampaignAudienceArgs"]],
        ["retval", "result", ["VRAPI::CalculateCampaignAudienceResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "calculateCampaignAudienceResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "canCallMethod"),
      "VR/API/1_0#canCallMethod",
      "canCallMethod",
      [ ["in", "args", ["VRAPI::CanCallMethodArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "canCallMethodArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "compileCampaignRecipientResults"),
      "VR/API/1_0#compileCampaignRecipientResults",
      "compileCampaignRecipientResults",
      [ ["in", "args", ["VRAPI::CompileCampaignRecipientResultsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "compileCampaignRecipientResultsArgs"]],
        ["retval", "result", ["VRAPI::CompileCampaignRecipientResultsResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "compileCampaignRecipientResultsResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "compileCampaignRecipientResultsBackground"),
      "VR/API/1_0#compileCampaignRecipientResultsBackground",
      "compileCampaignRecipientResultsBackground",
      [ ["in", "args", ["VRAPI::CompileCampaignRecipientResultsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "compileCampaignRecipientResultsArgs"]],
        ["retval", "background_task_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "compileSegmentationQuery"),
      "VR/API/1_0#compileSegmentationQuery",
      "compileSegmentationQuery",
      [ ["in", "args", ["VRAPI::CompileSegmentationQueryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "compileSegmentationQueryArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfList", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfList"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "compileSegmentationQueryBackground"),
      "VR/API/1_0#compileSegmentationQueryBackground",
      "compileSegmentationQueryBackground",
      [ ["in", "args", ["VRAPI::CompileSegmentationQueryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "compileSegmentationQueryArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "createEmailCampaign"),
      "VR/API/1_0#createEmailCampaign",
      "createEmailCampaign",
      [ ["in", "args", ["VRAPI::CreateEmailCampaignArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "createEmailCampaignArgs"]],
        ["retval", "result", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "createFile"),
      "VR/API/1_0#createFile",
      "createFile",
      [ ["in", "args", ["VRAPI::CreateFileArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "createFileArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "createList"),
      "VR/API/1_0#createList",
      "createList",
      [ ["in", "args", ["VRAPI::CreateListArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "createListArgs"]],
        ["retval", "list_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "createOptinForm"),
      "VR/API/1_0#createOptinForm",
      "createOptinForm",
      [ ["in", "args", ["VRAPI::CreateOptinFormArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "createOptinFormArgs"]],
        ["retval", "optin_form_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "createSegmentationQuery"),
      "VR/API/1_0#createSegmentationQuery",
      "createSegmentationQuery",
      [ ["in", "args", ["VRAPI::CreateSegmentationQueryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "createSegmentationQueryArgs"]],
        ["retval", "query_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "createSfList"),
      "VR/API/1_0#createSfList",
      "createSfList",
      [ ["in", "args", ["VRAPI::CreateSfListArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "createSfListArgs"]],
        ["retval", "result", ["VRAPI::AppendFileToListResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "appendFileToListResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "deleteCampaign"),
      "VR/API/1_0#deleteCampaign",
      "deleteCampaign",
      [ ["in", "args", ["VRAPI::DeleteCampaignArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "deleteCampaignArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "deleteFile"),
      "VR/API/1_0#deleteFile",
      "deleteFile",
      [ ["in", "args", ["VRAPI::DeleteFileArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "deleteFileArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "deleteList"),
      "VR/API/1_0#deleteList",
      "deleteList",
      [ ["in", "args", ["VRAPI::DeleteListArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "deleteListArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "deleteListMember"),
      "VR/API/1_0#deleteListMember",
      "deleteListMember",
      [ ["in", "args", ["VRAPI::DeleteListMemberArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "deleteListMemberArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "deleteSegmentationQuery"),
      "VR/API/1_0#deleteSegmentationQuery",
      "deleteSegmentationQuery",
      [ ["in", "args", ["VRAPI::DeleteSegmentationQueryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "deleteSegmentationQueryArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "deleteTemplateCampaignModule"),
      "VR/API/1_0#deleteTemplateCampaignModule",
      "deleteTemplateCampaignModule",
      [ ["in", "args", ["VRAPI::DeleteTemplateCampaignModuleArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "deleteTemplateCampaignModuleArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "downloadCampaignRecipientResults"),
      "VR/API/1_0#downloadCampaignRecipientResults",
      "downloadCampaignRecipientResults",
      [ ["in", "args", ["VRAPI::DownloadCampaignRecipientResultsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadCampaignRecipientResultsArgs"]],
        ["retval", "result", ["VRAPI::DownloadCampaignRecipientResultsResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadCampaignRecipientResultsResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "downloadCampaignRecipientResultsBackground"),
      "VR/API/1_0#downloadCampaignRecipientResultsBackground",
      "downloadCampaignRecipientResultsBackground",
      [ ["in", "args", ["VRAPI::DownloadCampaignRecipientResultsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadCampaignRecipientResultsArgs"]],
        ["retval", "background_task_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "downloadCompanyUnsubscribesAndBounces"),
      "VR/API/1_0#downloadCompanyUnsubscribesAndBounces",
      "downloadCompanyUnsubscribesAndBounces",
      [ ["in", "args", ["VRAPI::DownloadCompanyUnsubscribesAndBouncesArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadCompanyUnsubscribesAndBouncesArgs"]],
        ["retval", "result", ["VRAPI::DownloadCompanyUnsubscribesAndBouncesResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadCompanyUnsubscribesAndBouncesResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "downloadList"),
      "VR/API/1_0#downloadList",
      "downloadList",
      [ ["in", "args", ["VRAPI::DownloadListArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadListArgs"]],
        ["retval", "result", ["VRAPI::DownloadListResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadListResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "downloadListBackground"),
      "VR/API/1_0#downloadListBackground",
      "downloadListBackground",
      [ ["in", "args", ["VRAPI::DownloadListArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadListArgs"]],
        ["retval", "background_task_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "editCompany"),
      "VR/API/1_0#editCompany",
      "editCompany",
      [ ["in", "args", ["VRAPI::EditCompanyArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "editCompanyArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "editListAttribute"),
      "VR/API/1_0#editListAttribute",
      "editListAttribute",
      [ ["in", "args", ["VRAPI::EditListAttributeArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "editListAttributeArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "editListMember"),
      "VR/API/1_0#editListMember",
      "editListMember",
      [ ["in", "args", ["VRAPI::EditListMemberArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "editListMemberArgs"]],
        ["retval", "result", ["VRAPI::ListMember", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ListMember"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "editListMembers"),
      "VR/API/1_0#editListMembers",
      "editListMembers",
      [ ["in", "args", ["VRAPI::EditListMembersArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "editListMembersArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "editSegmentationQuery"),
      "VR/API/1_0#editSegmentationQuery",
      "editSegmentationQuery",
      [ ["in", "args", ["VRAPI::EditSegmentationQueryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "editSegmentationQueryArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "editUser"),
      "VR/API/1_0#editUser",
      "editUser",
      [ ["in", "args", ["VRAPI::EditUserArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "editUserArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "emptyTrash"),
      "VR/API/1_0#emptyTrash",
      "emptyTrash",
      [ ["in", "args", ["VRAPI::EmptyTrashArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "emptyTrashArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "enumerateEmailCampaigns"),
      "VR/API/1_0#enumerateEmailCampaigns",
      "enumerateEmailCampaigns",
      [ ["in", "args", ["VRAPI::EnumerateEmailCampaignsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "enumerateEmailCampaignsArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfEmailCampaign", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfEmailCampaign"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "enumerateFiles"),
      "VR/API/1_0#enumerateFiles",
      "enumerateFiles",
      [ ["in", "args", ["VRAPI::EnumerateFilesArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "enumerateFilesArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfFileSpec", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfFileSpec"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "enumerateLists"),
      "VR/API/1_0#enumerateLists",
      "enumerateLists",
      [ ["in", "args", ["VRAPI::EnumerateListsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "enumerateListsArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfList", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfList"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "enumerateSegmentationQueries"),
      "VR/API/1_0#enumerateSegmentationQueries",
      "enumerateSegmentationQueries",
      [ ["in", "args", ["VRAPI::EnumerateSegmentationQueriesArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "enumerateSegmentationQueriesArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfSegmentationQuery", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfSegmentationQuery"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "eraseListMembers"),
      "VR/API/1_0#eraseListMembers",
      "eraseListMembers",
      [ ["in", "args", ["VRAPI::EraseListMembersArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "eraseListMembersArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "fetchAppendFileToListBackgroundResult"),
      "VR/API/1_0#fetchAppendFileToListBackgroundResult",
      "fetchAppendFileToListBackgroundResult",
      [ ["in", "args", ["VRAPI::FetchBackgroundResultArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "fetchBackgroundResultArgs"]],
        ["retval", "result", ["VRAPI::AppendFileToListResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "appendFileToListResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "fetchCompileCampaignRecipientResultsBackgroundResult"),
      "VR/API/1_0#fetchCompileCampaignRecipientResultsBackgroundResult",
      "fetchCompileCampaignRecipientResultsBackgroundResult",
      [ ["in", "args", ["VRAPI::FetchBackgroundResultArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "fetchBackgroundResultArgs"]],
        ["retval", "result", ["VRAPI::CompileCampaignRecipientResultsResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "compileCampaignRecipientResultsResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "fetchDownloadCampaignRecipientResultsBackgroundResult"),
      "VR/API/1_0#fetchDownloadCampaignRecipientResultsBackgroundResult",
      "fetchDownloadCampaignRecipientResultsBackgroundResult",
      [ ["in", "args", ["VRAPI::FetchBackgroundResultArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "fetchBackgroundResultArgs"]],
        ["retval", "result", ["VRAPI::DownloadCampaignRecipientResultsResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadCampaignRecipientResultsResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "fetchDownloadListBackgroundResult"),
      "VR/API/1_0#fetchDownloadListBackgroundResult",
      "fetchDownloadListBackgroundResult",
      [ ["in", "args", ["VRAPI::FetchBackgroundResultArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "fetchBackgroundResultArgs"]],
        ["retval", "result", ["VRAPI::DownloadListResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "downloadListResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "fetchRunSegmentationQueryBackgroundResult"),
      "VR/API/1_0#fetchRunSegmentationQueryBackgroundResult",
      "fetchRunSegmentationQueryBackgroundResult",
      [ ["in", "args", ["VRAPI::FetchBackgroundResultArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "fetchBackgroundResultArgs"]],
        ["retval", "result_size", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getBackgroundTaskStatus"),
      "VR/API/1_0#getBackgroundTaskStatus",
      "getBackgroundTaskStatus",
      [ ["in", "args", ["VRAPI::GetBackgroundTaskStatusArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getBackgroundTaskStatusArgs"]],
        ["retval", "result", ["VRAPI::BackgroundTaskStatus", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "BackgroundTaskStatus"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getCampaignDomainCount"),
      "VR/API/1_0#getCampaignDomainCount",
      "getCampaignDomainCount",
      [ ["in", "args", ["VRAPI::GetCampaignDomainCountArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getCampaignDomainCountArgs"]],
        ["retval", "result", ["VRAPI::GetCampaignDomainCountResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getCampaignDomainCountResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getCompany"),
      "VR/API/1_0#getCompany",
      "getCompany",
      [ ["in", "args", ["VRAPI::GetCompanyArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getCompanyArgs"]],
        ["retval", "result", ["VRAPI::Company", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "Company"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getCompanySummary"),
      "VR/API/1_0#getCompanySummary",
      "getCompanySummary",
      [ ["in", "args", ["VRAPI::GetCompanySummaryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getCompanySummaryArgs"]],
        ["retval", "result", ["VRAPI::NVDictionary", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "NVDictionary"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getEmailCampaignDeclineHistory"),
      "VR/API/1_0#getEmailCampaignDeclineHistory",
      "getEmailCampaignDeclineHistory",
      [ ["in", "args", ["VRAPI::GetEmailCampaignDeclineHistoryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getEmailCampaignDeclineHistoryArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfEmailCampaignDecline", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfEmailCampaignDecline"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getEmailCampaignResponseHistograms"),
      "VR/API/1_0#getEmailCampaignResponseHistograms",
      "getEmailCampaignResponseHistograms",
      [ ["in", "args", ["VRAPI::GetEmailCampaignResponseHistogramsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getEmailCampaignResponseHistogramsArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfEmailCampaignResponseHistogram", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfEmailCampaignResponseHistogram"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getEmailCampaignStats"),
      "VR/API/1_0#getEmailCampaignStats",
      "getEmailCampaignStats",
      [ ["in", "args", ["VRAPI::GetEmailCampaignStatsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getEmailCampaignStatsArgs"]],
        ["retval", "result", ["VRAPI::EmailCampaignStats", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "EmailCampaignStats"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getEmailCreditBalance"),
      "VR/API/1_0#getEmailCreditBalance",
      "getEmailCreditBalance",
      [ ["in", "args", ["VRAPI::GetEmailCreditBalanceArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getEmailCreditBalanceArgs"]],
        ["retval", "result", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getListDomainCount"),
      "VR/API/1_0#getListDomainCount",
      "getListDomainCount",
      [ ["in", "args", ["VRAPI::GetListDomainCountArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getListDomainCountArgs"]],
        ["retval", "result", ["VRAPI::GetListDomainCountResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getListDomainCountResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getListMemberByAddressHash"),
      "VR/API/1_0#getListMemberByAddressHash",
      "getListMemberByAddressHash",
      [ ["in", "args", ["VRAPI::GetListMemberByAddressHashArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getListMemberByAddressHashArgs"]],
        ["retval", "result", ["VRAPI::ListMember", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ListMember"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getListMemberByEmailAddress"),
      "VR/API/1_0#getListMemberByEmailAddress",
      "getListMemberByEmailAddress",
      [ ["in", "args", ["VRAPI::GetListMemberByEmailAddressArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getListMemberByEmailAddressArgs"]],
        ["retval", "result", ["VRAPI::ListMember", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ListMember"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getListMemberByHash"),
      "VR/API/1_0#getListMemberByHash",
      "getListMemberByHash",
      [ ["in", "args", ["VRAPI::GetListMemberByHashArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getListMemberByHashArgs"]],
        ["retval", "result", ["VRAPI::ListMember", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ListMember"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getListMembers"),
      "VR/API/1_0#getListMembers",
      "getListMembers",
      [ ["in", "args", ["VRAPI::GetListMembersArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getListMembersArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfListMember", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfListMember"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getPricingStructure"),
      "VR/API/1_0#getPricingStructure",
      "getPricingStructure",
      [ ["in", "args", ["VRAPI::GetPricingStructureArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getPricingStructureArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfPricingStructureTier", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfPricingStructureTier"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getPurchaseQuotation"),
      "VR/API/1_0#getPurchaseQuotation",
      "getPurchaseQuotation",
      [ ["in", "args", ["VRAPI::GetPurchaseQuotationArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getPurchaseQuotationArgs"]],
        ["retval", "result", ["VRAPI::GetPurchaseQuotationResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getPurchaseQuotationResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getUser"),
      "VR/API/1_0#getUser",
      "getUser",
      [ ["in", "args", ["VRAPI::GetUserArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getUserArgs"]],
        ["retval", "result", ["VRAPI::User", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "User"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "getUserByEmailAddress"),
      "VR/API/1_0#getUserByEmailAddress",
      "getUserByEmailAddress",
      [ ["in", "args", ["VRAPI::GetUserByEmailAddressArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "getUserByEmailAddressArgs"]],
        ["retval", "result", ["VRAPI::User", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "User"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "launchEmailCampaign"),
      "VR/API/1_0#launchEmailCampaign",
      "launchEmailCampaign",
      [ ["in", "args", ["VRAPI::LaunchEmailCampaignArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "launchEmailCampaignArgs"]],
        ["retval", "args", ["VRAPI::LaunchEmailCampaignResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "launchEmailCampaignResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "login"),
      "VR/API/1_0#login",
      "login",
      [ ["in", "args", ["VRAPI::LoginArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "loginArgs"]],
        ["retval", "sessionId", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "moveFile"),
      "VR/API/1_0#moveFile",
      "moveFile",
      [ ["in", "args", ["VRAPI::MoveFileArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "moveFileArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "refresh"),
      "VR/API/1_0#refresh",
      "refresh",
      [ ["in", "args", ["VRAPI::RefreshArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "refreshArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "renderCampaignContent"),
      "VR/API/1_0#renderCampaignContent",
      "renderCampaignContent",
      [ ["in", "args", ["VRAPI::RenderCampaignContentArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "renderCampaignContentArgs"]],
        ["retval", "result", ["VRAPI::RenderCampaignContentResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "renderCampaignContentResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "runSegmentationQuery"),
      "VR/API/1_0#runSegmentationQuery",
      "runSegmentationQuery",
      [ ["in", "args", ["VRAPI::RunSegmentationQueryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "runSegmentationQueryArgs"]],
        ["retval", "result_size", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "runSegmentationQueryBackground"),
      "VR/API/1_0#runSegmentationQueryBackground",
      "runSegmentationQueryBackground",
      [ ["in", "args", ["VRAPI::RunSegmentationQueryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "runSegmentationQueryArgs"]],
        ["retval", "background_task_id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "searchListMembers"),
      "VR/API/1_0#searchListMembers",
      "searchListMembers",
      [ ["in", "args", ["VRAPI::SearchListMembersArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "searchListMembersArgs"]],
        ["retval", "result", ["VRAPI::ArrayOfListMember", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "ArrayOfListMember"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "sendEmailCampaignTest"),
      "VR/API/1_0#sendEmailCampaignTest",
      "sendEmailCampaignTest",
      [ ["in", "args", ["VRAPI::SendEmailCampaignTestArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "sendEmailCampaignTestArgs"]],
        ["retval", "args", ["VRAPI::SendEmailCampaignTestResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "sendEmailCampaignTestResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "setCampaignLists"),
      "VR/API/1_0#setCampaignLists",
      "setCampaignLists",
      [ ["in", "args", ["VRAPI::SetCampaignListsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "setCampaignListsArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "setCustomListFields"),
      "VR/API/1_0#setCustomListFields",
      "setCustomListFields",
      [ ["in", "args", ["VRAPI::SetCustomListFieldsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "setCustomListFieldsArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "setDisplayedListFields"),
      "VR/API/1_0#setDisplayedListFields",
      "setDisplayedListFields",
      [ ["in", "args", ["VRAPI::SetDisplayedListFieldsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "setDisplayedListFieldsArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "setEmailCampaignAttribute"),
      "VR/API/1_0#setEmailCampaignAttribute",
      "setEmailCampaignAttribute",
      [ ["in", "args", ["VRAPI::SetEmailCampaignAttributeArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "setEmailCampaignAttributeArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "setEmailCampaignContent"),
      "VR/API/1_0#setEmailCampaignContent",
      "setEmailCampaignContent",
      [ ["in", "args", ["VRAPI::SetEmailCampaignContentArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "setEmailCampaignContentArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "setIndexedListFields"),
      "VR/API/1_0#setIndexedListFields",
      "setIndexedListFields",
      [ ["in", "args", ["VRAPI::SetIndexedListFieldsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "setIndexedListFieldsArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "setTemplateCampaignModule"),
      "VR/API/1_0#setTemplateCampaignModule",
      "setTemplateCampaignModule",
      [ ["in", "args", ["VRAPI::SetTemplateCampaignModuleArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "setTemplateCampaignModuleArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "transferEmailCredits"),
      "VR/API/1_0#transferEmailCredits",
      "transferEmailCredits",
      [ ["in", "args", ["VRAPI::TransferEmailCreditsArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "transferEmailCreditsArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "undeleteCampaign"),
      "VR/API/1_0#undeleteCampaign",
      "undeleteCampaign",
      [ ["in", "args", ["VRAPI::UndeleteCampaignArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "undeleteCampaignArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "undeleteList"),
      "VR/API/1_0#undeleteList",
      "undeleteList",
      [ ["in", "args", ["VRAPI::UndeleteListArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "undeleteListArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "undeleteSegmentationQuery"),
      "VR/API/1_0#undeleteSegmentationQuery",
      "undeleteSegmentationQuery",
      [ ["in", "args", ["VRAPI::UndeleteSegmentationQueryArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "undeleteSegmentationQueryArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "unlaunchEmailCampaign"),
      "VR/API/1_0#unlaunchEmailCampaign",
      "unlaunchEmailCampaign",
      [ ["in", "args", ["VRAPI::UnlaunchEmailCampaignArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "unlaunchEmailCampaignArgs"]],
        ["retval", "result", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsC_1_0, "validateStreetAddress"),
      "VR/API/1_0#validateStreetAddress",
      "validateStreetAddress",
      [ ["in", "args", ["VRAPI::ValidateStreetAddressArgs", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "validateStreetAddressArgs"]],
        ["retval", "result", ["VRAPI::ValidateStreetAddressResult", "http://api.verticalresponse.com/1.0/VRAPI.xsd", "validateStreetAddressResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = VRAPIMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = VRAPIMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
